"""add participant key to conversation

Revision ID: 181f440078ea
Revises: e1b6dad7c36e
Create Date: 2026-02-03 07:31:43.390382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181f440078ea'
down_revision = 'e1b6dad7c36e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_key', sa.String(length=255), nullable=False))
        batch_op.create_index(batch_op.f('ix_conversations_participant_key'), ['participant_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_participant_key'))
        batch_op.drop_column('participant_key')

    # ### end Alembic commands ###
