"""add title to lesson instances

Revision ID: 29ebab5e8f93
Revises: de29441ee938
Create Date: 2026-01-27 16:54:53.502385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ebab5e8f93'
down_revision = 'de29441ee938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overwrite_title', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_instances', schema=None) as batch_op:
        batch_op.drop_column('overwrite_title')

    # ### end Alembic commands ###
