"""add status to user

Revision ID: a7aea32745a0
Revises: 36617d26d9cb
Create Date: 2026-01-29 15:05:27.984614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7aea32745a0'
down_revision = '36617d26d9cb'
branch_labels = None
depends_on = None


def upgrade():
    sa.Enum(
        'inactive',
        'active',
        'disabled',
        name='activation_status'
    ).create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('inactive', 'active', 'disabled', name='activation_status'), server_default='inactive', nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
