"""add original_lesson_occurence_date to lesson instances

Revision ID: bc380a62e872
Revises: 29ebab5e8f93
Create Date: 2026-01-27 17:26:25.513915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc380a62e872'
down_revision = '29ebab5e8f93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_lesson_occurence_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_instances', schema=None) as batch_op:
        batch_op.drop_column('original_lesson_occurence_date')

    # ### end Alembic commands ###
