"""add display order to levels

Revision ID: de29441ee938
Revises: d58197190e6b
Create Date: 2026-01-23 10:04:49.020635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de29441ee938'
down_revision = 'd58197190e6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach_levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach_levels', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    # ### end Alembic commands ###
