"""change field names for lesson usage

Revision ID: f192ac1b30c2
Revises: ecf79220576d
Create Date: 2026-01-21 18:51:03.725973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f192ac1b30c2'
down_revision = 'ecf79220576d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_datetime', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_datetime', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('recurrence_end', sa.Date(), nullable=True))
        batch_op.alter_column('is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('date')
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    with op.batch_alter_table('coach_levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=10), nullable=False))

    with op.batch_alter_table('lesson_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_datetime', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_datetime', sa.DateTime(), nullable=False))
        batch_op.drop_constraint('lesson_instances_club_id_fkey', type_='foreignkey')
        batch_op.drop_column('club_id')
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_datetime', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_datetime', sa.DateTime(), nullable=False))
        batch_op.alter_column('recurrence_end',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.alter_column('recurrence_end',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.drop_column('end_datetime')
        batch_op.drop_column('start_datetime')

    with op.batch_alter_table('lesson_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('club_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('lesson_instances_club_id_fkey', 'clubs', ['club_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('end_datetime')
        batch_op.drop_column('start_datetime')

    with op.batch_alter_table('coach_levels', schema=None) as batch_op:
        batch_op.drop_column('code')

    with op.batch_alter_table('calendar_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.alter_column('is_recurring',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('recurrence_end')
        batch_op.drop_column('end_datetime')
        batch_op.drop_column('start_datetime')

    # ### end Alembic commands ###
